# Generated by Django 5.2.6 on 2025-09-23 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("vaccination", "Vaccination"),
                            ("sickness", "Sickness"),
                            ("check-up", "Check-up"),
                            ("treatment", "Treatment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AMURecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_name", models.CharField(max_length=100)),
                ("dosage", models.CharField(max_length=50)),
                (
                    "withdrawal_period",
                    models.PositiveIntegerField(
                        help_text="Days until livestock product is safe for consumption"
                    ),
                ),
                (
                    "health_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amu_records",
                        to="livestock.healthrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Livestock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_id", models.CharField(max_length=100, unique=True)),
                ("species", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("sick", "Sick"),
                            ("recovering", "Recovering"),
                        ],
                        default="healthy",
                        max_length=20,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="livestock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_records",
                to="livestock.livestock",
            ),
        ),
    ]
