# Generated by Django 5.2.6 on 2025-09-23 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livestock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_type", models.CharField(max_length=100)),
                ("quantity_kg", models.DecimalField(decimal_places=2, max_digits=7)),
                ("date", models.DateField()),
                (
                    "livestock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_records",
                        to="livestock.livestock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YieldRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "yield_type",
                    models.CharField(help_text="e.g., Milk, Eggs", max_length=50),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "unit",
                    models.CharField(help_text="e.g., Liters, Units", max_length=20),
                ),
                ("date", models.DateField()),
                (
                    "livestock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yield_records",
                        to="livestock.livestock",
                    ),
                ),
            ],
        ),
    ]
