# Generated by Django 5.2.6 on 2025-09-24 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_remove_livestock_owner_farm_livestock_farm_labourer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active_ingredient', models.CharField(blank=True, max_length=100, null=True)),
                ('species_target', models.CharField(blank=True, max_length=100, null=True)),
                ('recommended_dosage_min', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('recommended_dosage_max', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='amurecord',
            name='drug_name',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='treatment_outcome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='current_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='amurecord',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amu_records', to='livestock.drug'),
        ),
    ]
